export const REPOSITORIES = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  REPORT_REPOSITORY: 'REPORT_REPOSITORY',
  DASHBOARD_REPOSITORY: 'DASHBOARD_REPOSITORY',
  USER_DASHBOARD_REPOSITORY: 'USER_DASHBOARD_REPOSITORY',
  CONVERSATION_REPOSITORY: 'CONVERSATION_REPOSITORY',
  MESSAGE_REPOSITORY: 'MESSAGE_REPOSITORY',
  // GROUP_CONVERSATION_PARTICIPANT_REPOSITORY: 'GROUP_CONVERSATION_PARTICIPANT_REPOSITORY',
  DASHBOARD_INVITATION_REPOSITORY: 'DASHBOARD_INVITATION_REPOSITORY'
};